export const GET_ALL_STICKERS = 'GET_ALL_STICKERS';
export const SET_ALL_STICKER_SETS = 'SET_ALL_STICKER_SETS';
export const LOAD_STICKER_SET = 'LOAD_STICKER_SET';
export const SET_STICKER_PACKS = 'SET_STICKER_PACKS';
export const SET_DOCUMENT = 'SET_DOCUMENT';
export const SET_DOCUMENT_BATCH = 'SET_DOCUMENT_BATCH';
