export const LOAD_DIALOGS = 'LOAD_DIALOGS';
export const DIALOGS_LOAD_FAILED = 'DIALOGS_LOAD_FIALED';
export const DIALOGS_LOADED = 'DIALOGS_LOADED';
export const ADD_MESSAGE = 'ADD_MESSAGE';
export const PREPEND_MESSAGE = 'PREPEND_MESSAGE';
export const DELETE_MESSAGE = 'DELETE_MESSAGE';
export const ADD_MESSAGES_BATCH = 'ADD_MESSAGES_BATCH';
export const SET_ACTIVE_DIALOG = 'SET_ACTIVE_DIALOG';
export const SET_SEARCHED_DIALOG_MESSAGES = 'SET_SEARCHED_DIALOG_MESSAGES';
export const CLEAR_SEARCHED_DIALOG_MESSAGES = 'CLEAR_SEARCHED_DIALOG_MESSAGES';

export const LOAD_DIALOG_HISTORY = 'LOAD_DIALOG_HISTORY';
export const SEARCH_DIALOG_MESSAGES = 'SEARCH_DIALOG_MESSAGES';
export const SEND_MESSAGE = 'SEND_MESSAGE';
export const SEND_MEDIA = 'SEND_MEDIA';
