export const LOAD_DIALOGS = 'LOAD_DIALOGS';
export const DIALOGS_LOAD_FAILED = 'DIALOGS_LOAD_FIALED';
export const DIALOGS_LOADED = 'DIALOGS_LOADED';
export const ADD_MESSAGE = 'ADD_MESSAGE';
export const ADD_MESSAGES_BATCH = 'ADD_MESSAGES_BATCH';
export const SET_ACTIVE_DIALOG = 'SET_ACTIVE_DIALOG';
export const LOAD_DIALOG_HISTORY = 'LOAD_DIALOG_HISTORY';